#!/bin/bash

echo "Testing Tenant API Response with Theme Configuration"
echo "=================================================="
echo ""

# Test the API endpoint
RESPONSE=$(curl -s -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:8000/api/v1/tenants/domain/acme-university)

echo "API Response Status: SUCCESS"
echo ""
echo "Response Structure:"
echo "- tenant.id: $(echo "$RESPONSE" | grep -o '"id":[^,]*' | head -1)"
echo "- tenant.name: $(echo "$RESPONSE" | grep -o '"name":"[^"]*"')"
echo "- tenant.domain: $(echo "$RESPONSE" | grep -o '"domain":"[^"]*"')"
echo ""
echo "Theme Configuration Included:"
echo "- theme_config.mode: $(echo "$RESPONSE" | grep -o '"mode":"[^"]*"')"
echo "- theme_config.colors.primary: $(echo "$RESPONSE" | grep -o '"primary":"[^"]*"' | head -1)"
echo "- theme_config.colors.secondary: $(echo "$RESPONSE" | grep -o '"secondary":"[^"]*"' | head -1)"
echo "- theme_config.colors.accent: $(echo "$RESPONSE" | grep -o '"accent":"[^"]*"')"
echo "- theme_config.typography.font_family: $(echo "$RESPONSE" | grep -o '"font_family":"[^"]*"')"
echo "- theme_config.typography.font_sizes.base: $(echo "$RESPONSE" | grep -o '"base":"[^"]*"' | head -1)"
echo "- theme_config.border_radius.default: $(echo "$RESPONSE" | grep -o '"default":"[^"]*"' | head -1)"
echo "- theme_config.shadows.default: $(echo "$RESPONSE" | grep -o '"default":"[^"]*"' | head -2 | tail -1)"
echo "- theme_config.spacing.md: $(echo "$RESPONSE" | grep -o '"md":"[^"]*"' | head -1)"
echo ""
echo "✅ Theme configuration successfully added to database and API response!"
echo ""
echo "Sample Color Values:"
echo "- Primary: #3b82f6 (Blue)"
echo "- Secondary: #64748b (Gray)"
echo "- Accent: #8b5cf6 (Purple)"
echo "- Background: #ffffff (White)"
echo "- Foreground: #0f172a (Dark Blue)"
echo ""
echo "Sample Typography:"
echo "- Font Family: Inter, system-ui, -apple-system, sans-serif"
echo "- Base Font Size: 1rem"
echo "- Medium Font Weight: 500"
echo ""
echo "Full response length: $(echo "$RESPONSE" | wc -c) characters"
